diff --git a/Makefile b/Makefile
index 2efae9f..a6ed54d 100644
--- a/Makefile
+++ b/Makefile
@@ -3,6 +3,7 @@
 
 GCC     := /tools/cad/riscv/rv32ima/bin/riscv32-unknown-elf-gcc
 GPP     := /tools/cad/riscv/rv32ima/bin/riscv32-unknown-elf-g++
+LINK    := $(patsubst %-g++,%-ar,$(GPP))
 OBJCOPY := /tools/cad/riscv/rv32ima/bin/riscv32-unknown-elf-objcopy
 OBJDUMP := /tools/cad/riscv/rv32ima/bin/riscv32-unknown-elf-objdump
 VIVADO  := /tools/Xilinx/Vivado/2024.1/bin/vivado
@@ -10,7 +11,7 @@ VPP     := /tools/Xilinx/Vitis/2024.1/bin/v++
 RTLSIM  := /tools/cad/bin/verilator
 
-TARGET := arty_a7
-#TARGET := cmod_a7
+#TARGET := arty_a7
+TARGET := cmod_a7
 #TARGET := nexys_a7
 
 USE_HLS ?= 0
@@ -18,13 +19,18 @@ USE_HLS ?= 0
 .PHONY: build prog run clean
 all: prog build
 
-build:
+build: prog
 	$(RTLSIM) --binary --trace --top-module top --Wno-WIDTHTRUNC --Wno-WIDTHEXPAND -o top *.v
 	gcc -O2 dispemu/dispemu.c -o build/dispemu -lcairo -lX11
 
 prog:
 	mkdir -p build
-	$(GCC) -Os -march=rv32im -mabi=ilp32 -nostartfiles -Iapp -Tapp/link.ld -o build/main.elf app/crt0.s app/*.c *.c
+	$(GPP) -Os -IMadgwick -Iapp -march=rv32im -mabi=ilp32 -c Madgwick/MadgwickAHRS.cpp -o build/MadgwickAHRS.o
+	$(LINK) rcs build/libmadgwick.a build/MadgwickAHRS.o
+	$(GPP) -Os -IMadgwick -Iapp -march=rv32im -mabi=ilp32 -c main.cpp -o build/main.o
+	$(GPP) -Os -IMadgwick -Iapp -march=rv32im -mabi=ilp32 -nostartfiles -Tapp/link.ld \
+		-o build/main.elf app/crt0.s app/*.c build/main.o -Lbuild -lmadgwick -lm
+	rm -f build/MadgwickAHRS.o build/libmadgwick.a build/main.o
 	make initf
 
 imem_size =	$(shell grep -oP "\`define\s+IMEM_SIZE\s+\(\K[^)]*" config.vh | bc)
@@ -76,6 +82,7 @@ bit:
 	fi
 	$(VIVADO) -mode batch -source build.tcl -tclargs $(TCL_ARG)
 	cp vivado/main.runs/impl_1/main.bit build/.
+	cp vivado/main.runs/impl_1/main.bin build/.
 	@if [ -f vivado/main.runs/impl_i/main.ltx ]; then \
 		cp -f vivado/main.runs/impl_i/main.ltx build/.; \
 	fi
